# Generated by Django 3.2 on 2021-06-17 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PcsmEqpto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('eqpto_sap_cod', models.CharField(max_length=255, unique=True)),
                ('eqpto_descricao', models.CharField(max_length=255)),
                ('eqpto_abc_cod', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PcsmOm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('om_sap_cod', models.CharField(max_length=255)),
                ('om_pcsm_cod', models.CharField(max_length=255)),
                ('om_descricao', models.TextField(blank=True, default='')),
                ('om_tipo_ord', models.CharField(max_length=255)),
                ('om_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.pcsmeqpto')),
                ('om_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Om',
                'verbose_name_plural': "Om's",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PcsmAptoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('aptocons_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('aptocons_om_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcsmom')),
            ],
            options={
                'verbose_name': 'Apontamento Saldo',
                'verbose_name_plural': 'Apontamentos Saldos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PcsmApto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('apto_inio', models.DateTimeField(blank=True, null=True)),
                ('apto_fim', models.DateTimeField(blank=True, null=True)),
                ('apto_om_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pcsmom')),
                ('apto_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['id'],
            },
        ),
    ]
