# Generated by Django 3.2 on 2021-06-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcsmapto',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pcsmaptosaldo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pcsmeqpto',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pcsmom',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
