# Generated by Django 3.2 on 2021-06-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210617_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcsmapto',
            options={'ordering': ['id'], 'verbose_name': 'Apontamento', 'verbose_name_plural': 'Apontamentos'},
        ),
        migrations.RenameField(
            model_name='pcsmapto',
            old_name='apto_inio',
            new_name='apto_inicio',
        ),
    ]
